### ISSUE TITLE
Plassering av skos:example

### ISSUE THREAD

**Issue by jimjyang** [Informasjonsforvaltning/concepttordf#3]
https://github.com/Informasjonsforvaltning/concepttordf/blob/8ebf24f71999ec08a55029fe481a580597cea08e/tests/completeconcept.ttl#L49

skos:example bør plasseres inne i skosno:definisjon / skosno:alternativFormulering, dvs. tilsvarende som skosno:omfang. 

(Dette i henhold til dagens versjon av [Forvaltningsstandard for begerepsbeskrivelser](https://doc.difi.no/data/forvaltningsstandard-begrepsbeskrivelser/#vedlegga), selv om standarden burde har modellert dette annerledes, jf. [Issue #9](https://github.com/difi/forvaltningsstandard-begrep/issues/9) for standarden).

**Comment by stigbd** [comment]
Fixa i 8a14851
