### ISSUE TITLE
Mangler eksempel på skosno:datastrukturterm

### ISSUE THREAD

**Issue by jimjyang** [Informasjonsforvaltning/concepttordf#4]
https://github.com/Informasjonsforvaltning/concepttordf/blob/8ebf24f71999ec08a55029fe481a580597cea08e/tests/completeconcept.ttl#L58

Bør føye til et eksempel på [datastrukturterm](https://doc.difi.no/data/begrep-skos-ap-no/#_begrep_datastrukturterm) i dette komplette eksemplet.

**Comment by stigbd** [comment]
Fiksa i 6484614
