### ISSUE TITLE
URI til dcatno

### ISSUE THREAD

**Issue by jimjyang** [Informasjonsforvaltning/concepttordf#5]
https://github.com/Informasjonsforvaltning/concepttordf/blob/a15f56943cab50e705f162ee551a250fd1b7a45f/tests/completeconcept.ttl#L17

blir data.norge.no/vocabulary/dcatno#

**Comment by stigbd** [comment]
Det viste seg at dette namespacet ikkje var i bruk, så eg fjerna. Forøvrig må vi bestemme om vi skal bruke `http` eller `https` i schema-delen av url.
Løst i 0381c15
