### ISSUE TITLE
Tried to install with Python 3.9

### ISSUE THREAD

**Issue by olesjo** [Informasjonsforvaltning/concepttordf#7]
I tried to run pip install concepttordf. I have Python 3.9.0 installed. Seems that it lacks support for that version?

![image](https://user-images.githubusercontent.com/17745364/100330158-e2d04300-2fce-11eb-87bb-d8364117993e.png)

**Comment by stigbd** [comment]
You should verify that your version of pip is the version included in your current environment. E.g.
```
> pip --version
> python --version
```
Should show e.g. `Python 3.9.0`

**Comment by stigbd** [comment]
The requirement of concepttordf is Python >=3.7, <4.0 as documented here: https://pypi.org/project/concepttordf/

Please report back if it still an issue.

**Comment by stigbd** [comment]
Library is tested with Python 3.9. Closing.
